#ifndef __PAL_TADI_MOUSE_SYMBOLS_H__
#define __PAL_TADI_MOUSE_SYMBOLS_H__

#define MB_LEFT_INDEX		1
#define MB_MIDDLE_INDEX		2
#define MB_RIGHT_INDEX		3
#define MB_WHEELUP_INDEX	4
#define MB_WHEELDOWN_INDEX	5

#define MB_LEFT_MASK		0x1
#define MB_MIDDLE_MASK		0x2
#define MB_RIGHT_MASK		0x4
#define MB_WHEELUP_MASK		0x8
#define MB_WHEELDOWN_MASK	0x10

#endif
